name: Deploy on Rasberry


on:
  push:
    branches: [master,main]

  workflow_dispatch:


jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: deploy
        run: python manage.py runserver