name: Deploy on Rasberry


on:
  push:
    branches: [master,main]

  workflow_dispatch:


jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          submodules: recursive
      - run: git rm --cached backend/src/CreateWPblog
      - run: git submodule init
      - run: git submodule update --init --recursive